get http://localhost:3000/states/

###

get http://localhost:3000/states/8/

###

POST http://localhost:3000/districts/
Content-Type: application/json

{
    "districtName": "Bagalkot",
    "stateId": 3,
    "cases": 2323,
    "cured": 2000,
    "active": 315,
    "deaths": 8
}

###
get http://localhost:3000/districts/321/

###

delete http://localhost:3000/districts/322/

###

put http://localhost:3000/districts/321/
Content-Type: application/json

{
    "districtName": "Nadia",
    "stateId": 3,
    "cases": 9628,
    "cured": 6524,
    "active": 3000,
    "deaths": 104
}

### 

get http://localhost:3000/states/8/stats/

###

get http://localhost:3000/districts/321/details/